Add missed outputs parameter
Fix TypeError: click() missing 1 required positional argument 'outputs'. This should be empty or None, because save_config returns None